Add initial unit tests
vacuumlabs/obedbot pull request #86
Opened 2018-02-05 16:26 UTC by matejkrajcovic

2018-02-08 08:40 UTC, misogl requested changes
I don't find the tests very useful. You test only basic orders and don't test invalid orders (just non-orders).
Also: why did you amend someone's else commit that was 1 year old? I would expect a rebase and a separate fix commit.
BTW: the original rename of `isChannelPublic` to `isChannelMain` was a good change.

2018-02-08 08:40 UTC, misogl commented on .travis.yml
> +notifications:
We don't use Travis anymore.

2018-02-08 08:40 UTC, misogl commented on package.json
> +    "test": "yarn run build && yarn run eslint && yarn run mocha",
You should run build after `eslint`.

2018-02-08 08:40 UTC, misogl commented on config.js
> +require('dotenv').config({path: process.env.TEST ? './.env.test' : './.env'});
`process.env.CIRCLECI` is already defined.

2018-02-12 12:22 UTC, matejkrajcovic commented
@misogl These are only basic unit tests to prepare infrastructure. In #85 I add new regexp tests.

2018-02-12 13:14 UTC, misogl requested changes

2018-02-12 13:14 UTC, misogl commented on package.json
> +    "mocha": "CIRCLECI=1 mocha --require babel-core/register"
`CIRCLECI` is already defined.

2022-04-06 15:50 UTC, closed without merging