get hamka data from website not printed menu
vacuumlabs/obedbot pull request #99
Opened 2018-10-16 16:32 UTC by Zygro

2018-11-04 22:03 UTC, misogl requested changes
Please also put the new URL for hamka menu to `.env.template` (`OBEDBOT_HAMKA` env variable).

2018-11-04 22:03 UTC, misogl commented on package.json
>      "babel-register": "^6.26.0",
We should switch all babel packages to scoped names (`@babel/register`).

2018-11-05 10:24 UTC, Zygro commented on .eslintrc
> +  },
added this because of https://github.com/eslint/eslint/issues/4344

2018-11-07 12:25 UTC, conqeror approved these changes

2018-11-07 22:41 UTC, misogl commented
The hamka menu is now fixed. If it stops working again we can fix it by merging this PR.

2019-09-03 12:53 UTC, closed without merging